### ISSUE TITLE
Next Launch timer too slow

### ISSUE THREAD

**Issue by lordpomeroy** [r-spacex/spacexstats-react#21]
If you open the stats page the launch timer is running a little bit too slow. I had it open for about an hour to track the next launch (Zuma) and it lost about 10 mins so an considerable amount.

I assume the timer initiates once with the time from the api and then runs in the JS on the client and that thread was too slow.

Proposition would be:
a) change the JS on client to avoid this
b) regulary resync with the server (this would also avoid missing a scrub or postponmend during an open window)

I dont know how many people use the page for this pupose so maybe it is a low priority issue.

**Comment by vlinder** [comment]
It is drifting because it uses an interval to count down the seconds one at a time. Intervals are not guaranteed to fire exactly each 1000ms. Also, if the computer goes to sleep it wont fire at all. Intervals can also slow down if you change tab.

Instead of increasing/decreasing a counter every 1000 ms, one should diff the current time and the target time on every interval.
