### ISSUE TITLE
Rename "used" to "Flight-Proven" ?

### ISSUE THREAD

**Issue by jakubsacha** [r-spacex/spacexstats-react#32]
What do you guys think about it?

**Comment by jhpratt** [comment]
I'm 99% certain I actually requested it be 'used', as it's more self-evident what it means to non-fans.

**Comment by jakubsacha** [comment]
It came through my mind since this is how SpaceX is calling the cores. I think they try somehow to remove pejorative meaning from the fact that core actually flight already.

Feel free to won't fix and close the issue ;-)

**Comment by jhpratt** [comment]
@AlbericTrancart thoughts?

**Comment by AlbericTrancart** [comment]
Actually I don't see any "reused" or "flight-proven" anywhere in the site :slightly_smiling_face: 
(I may or may not have been intentional to avoid the issue :stuck_out_tongue: )

The only occurrence I found is "The ${reuseHistoryData.mostReflownCore.core} booster is the one who flew the most, it was used for these missions" but it does include the first mission so there is no "reuse" dilemma in this case.
